### PR TITLE
add initial tests for ipfs class

### PR DESCRIPTION
**Pull request by cdeng001**

### CODE REVIEW

**Comment by daviddahl** [comment]
is this ready for review?

**Comment by cdeng001** [comment]
yeah, lmk if i missed or messed anything up

**Comment by cdeng001** [comment]
```
const res = await ipfs.saveProofToIpfs("peaches");
expect(res)
      .to.be.an.instanceOf(Array)
      .that.has.same.deep.members([{ hash: "sneaky peaches" }]);
```
using done would refractor to
```
ipfs.saveProofToIpfs("peaches")
    .then((res) => {
        expect(res)
          .to.be.an.instanceOf(Array)
          .that.has.same.deep.members([{ hash: "sneaky peaches" }]);
    } ).then(() => {
        done()
    })
```
is this correct?

**Comment by daviddahl** [comment]
You can just call done after the `expect()` and not use a second `.then()`

**Pull request merged**
